#!/usr/bin/env python3

a = """............o............
...........ooo...........
..........ooooo..........
.........ooooooo.........
........oo#ooo##o........
.......ooo#ooo#ooo.......
......oo###ooo#oooo......
.....oooo.oooo#ooooo.....
....oooooooooo#oooooo....
...ooo#########ooooooo...
..ooooo.......ooooooooo..
#########################"""

M = dict()
M['.'] = 0
M['#'] = 0
M['o'] = 0
for l in a.split('\n')[0:-1]:
    for c in l:
        M[c] += 1

print(M)

h = 11
r = 1
maxS = 0
for i in range(h):
    maxS += r
    r += 2
print(maxS)
